### ISSUE TITLE
Issue with HTTPS in Mono

### ISSUE THREAD

**Issue by mgsdk** [KSP-CKAN/CKAN-support#107]
KerbalStuff has updated their SSL configuration to remove an insecure cipher (RC4), with the result that Mono throws an exception when trying to connect to that site.

The error thrown is ```System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.```

There is an error report on the official bug tracker which has some similarity, https://bugzilla.xamarin.com/show_bug.cgi?id=19031. This bug report states the lack of support for the ECDHE cipher, which is one of two cipher families (As far as I can tell) that is available on kerbalstuff, with the other being DHE. Looking at the Mono sources there appears to be support for DHE.

Testing the issue can be done by running ```certmgr -ssl -v https://kerbalstuff.com```. We probably need to make a wrapper on openssl to fix this issue.

Useful resource for getting the SSL information:
https://www.ssllabs.com/ssltest/analyze.html?d=kerbalstuff.com

**Comment by Dazpoet** [comment]
Current effects of this appear to be:
- CKAN and NetKAN won't play nice with mods hosted on KerbalStuff on OS's depending on mono
- Jenkins report failure on all PRs based on `$kref` pointing to KerbalStuff in NetKAN
- Users recieve a somewhat cryptic warning saying `error: Error: SendFailure (Error writing headers)` when attempting an operation affected by this issue

Reproduction steps:
- Run CKAN using mono on any OS (including Windows, tested on Win 7)
- Attempt to install e.g FerramAerospaceResearch or any mod hosted on KS
- Recieve error message

**Comment by Qazerowl** [comment]
Is there a work around? Is this a fault on mono's part, kerbalstuff's part, or ckan's? A majority of mods are now impossible to download though ckan for me.

**Comment by Dazpoet** [comment]
The only possible "work around" for now is probably to run Windows, where CKAN appears to work normally.

**Comment by pjf** [comment]
Dang it. Can reproduce on my system, too.

**Comment by pjf** [comment]
CC'ing in @SirCmpwn, and actively searching for solutions now. Having mono only implement a subset of commonly used ciphers is definitely a pain!

**Comment by techman83** [comment]
Indeed not many at all.
https://github.com/mono/mono/blob/master/mcs/class/Mono.Security/Mono.Security.Protocol.Tls/CipherSuiteFactory.cs

```c#
			// Supported ciphers
			scs.Add((0x00 << 0x08) | 0x35, "TLS_RSA_WITH_AES_256_CBC_SHA", CipherAlgorithmType.Rijndael, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 32, 32, 256, 16, 16);
			scs.Add((0x00 << 0x08) | 0x2F, "TLS_RSA_WITH_AES_128_CBC_SHA", CipherAlgorithmType.Rijndael, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 16, 16, 128, 16, 16);
			scs.Add((0x00 << 0x08) | 0x0A, "TLS_RSA_WITH_3DES_EDE_CBC_SHA", CipherAlgorithmType.TripleDes, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 24, 24, 168, 8, 8);
			scs.Add((0x00 << 0x08) | 0x05, "TLS_RSA_WITH_RC4_128_SHA", CipherAlgorithmType.Rc4, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, false, 16, 16, 128, 0, 0);
			scs.Add((0x00 << 0x08) | 0x04, "TLS_RSA_WITH_RC4_128_MD5", CipherAlgorithmType.Rc4, HashAlgorithmType.Md5, ExchangeAlgorithmType.RsaKeyX, false, false, 16, 16, 128, 0, 0);
			scs.Add((0x00 << 0x08) | 0x09, "TLS_RSA_WITH_DES_CBC_SHA", CipherAlgorithmType.Des, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 8, 8, 56, 8, 8);

			// Supported ciphers
			scs.Add((0x00 << 0x08) | 0x35, "SSL_RSA_WITH_AES_256_CBC_SHA", CipherAlgorithmType.Rijndael, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 32, 32, 256, 16, 16);
			scs.Add((0x00 << 0x08) | 0x2F, "SSL_RSA_WITH_AES_128_CBC_SHA", CipherAlgorithmType.Rijndael, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 16, 16, 128, 16, 16);
			scs.Add((0x00 << 0x08) | 0x0A, "SSL_RSA_WITH_3DES_EDE_CBC_SHA", CipherAlgorithmType.TripleDes, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 24, 24, 168, 8, 8);
			scs.Add((0x00 << 0x08) | 0x05, "SSL_RSA_WITH_RC4_128_SHA", CipherAlgorithmType.Rc4, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, false, 16, 16, 128, 0, 0);
			scs.Add((0x00 << 0x08) | 0x04, "SSL_RSA_WITH_RC4_128_MD5", CipherAlgorithmType.Rc4, HashAlgorithmType.Md5, ExchangeAlgorithmType.RsaKeyX, false, false, 16, 16, 128, 0, 0);
			scs.Add((0x00 << 0x08) | 0x09, "SSL_RSA_WITH_DES_CBC_SHA", CipherAlgorithmType.Des, HashAlgorithmType.Sha1, ExchangeAlgorithmType.RsaKeyX, false, true, 8, 8, 56, 8, 8);
```

And no Diffie–Hellman based chipers which seems to be the only ones listed for KerbelStuff.

https://www.ssllabs.com/ssltest/analyze.html?d=https%3A%2F%2Fkerbalstuff.com

**Comment by pjf** [comment]
I have [Curlsharp](https://github.com/masroore/CurlSharp) compiled and running. Trying to see if I can get CKAN to use it as a fallback now.

**Comment by pjf** [comment]
And I may have a workaround which is not at all pretty, but which  *seems* to be doing the right thing. It *won't* report progress in the GUI or command line when using curlsharp, but it's better than failing entirely.

My build is [https://dl.dropboxusercontent.com/u/9702672/KSP/ckan-support-107.exe](here), and I would *love testers*. (If it works, then PRs to follow shortly.)

**Comment by Dazpoet** [comment]
Just tried installing ODFC and SatBatts (first KS mods I knew identifiers for and didn't have cached) on OS X with that version, not getting the errors the normal version give me.

Solution appears "slow" though, but I'm on an at times shaky wifi so that might be it. I got the impression github repos took longer to connect, once again might be wifi. Can I activate debug or something and feed more info to you?

**Comment by pjf** [comment]
@Dazpoet : Thank you so much! :) It should be slower insofar that it's no longer downloading files in parallel from KerbalStuff. It shouldn't be slower with downloads from github.

**Comment by pjf** [comment]
And yes, you can run it with `--debug` to see when it's falling back, but I don't expect that to provide much in the way of timing information.

**Comment by Dazpoet** [comment]
I assume this is the relevant part of the -debug log http://pastebin.com/6tA8D0wA

**Comment by pjf** [comment]
And the new release is out which has hotfixes for this.

Huge kudos to @masroore for CurlSharp, which proved to be delightfully easy to use and saved the day!

**Comment by Dazpoet** [comment]
This workaround appears to have a slowing effect on certain installs. https://github.com/KSP-CKAN/NetKAN/pull/877 keeps timing out on Jenkins, works fine on my windows 7 install and eventually works on my OS X machine.

Installation time under Windows 7 was ~1 minute
Installation time under OS X was ~30 minutes

**Comment by pjf** [comment]
Gosh dang it.

**Comment by Dazpoet** [comment]
Currently running the SETI-0.8.5.ckan file with `mono ckan.exe install --debug -c SETI-0.8.5.ckan` and I noticed that this happens for KS mods

```
431227 [16] INFO CKAN.NetAsyncDownloader (null) - Failed async download of https://kerbalstuff.com/mod/496/Contract Science Modifier/download/0.4 attempting hacky fallback
431228 [16] DEBUG CKAN.Net (null) - Downloading https://kerbalstuff.com/mod/496/Contract Science Modifier/download/0.4 to /var/folders/lf/l19k91w106s4lxm74kyw6sl00000gn/T/CdFileMgr/e7add2c8-3c2f-4a.tmp
531237 [16] INFO CKAN.Net (null) - Download failed, trying with curlsharp...
532602 [16] DEBUG CKAN.Net (null) - curlsharp download successful
```
I assume the numbers at the start of each line is some kind of time indicator? Either way it always seem to have about a 100 000 diff for all mods. I'm thinking that the 'hacky fallback' first attempts a download in some way that doesn't work and then retreats to using curlsharp after the first download times out or something similar. Not sure if that makes sense but it's the only thing I can come up with to explain the behaviour I'm seeing.

The mod in the example above is a 35kb .zip and I'm on a 100Mbit connection so it should not be bandwidth limited in any way.

**Comment by pjf** [comment]
Aye, the first number is milliseconds elapsed, so for some reason we're not kicking in with the curlsharp implementation for 100 seconds. Once it's downloaded I hope the install should be pretty fast.

I'm not sure what would be causing the 100s lag. A *proper* fix would be going straight to curlsharp on appropriate systems, so hopefully this can be avoided even if we don't know what's causing it.

**Comment by Dazpoet** [comment]
Seeing as the .ckan file I've used acctually isn't in the repositories I thought I'd try the same thing with a tried and tested file just to make sure. So I installed RealismOverhaul and lo and behold this hacky fallback acctually solved a totally unrelated issue! RO usually fail for me due to 403s from github, however the fallback now do a second attempt for those files after the first round of Async downloads are done and successfully downloaded everything.

Back to the main issue, the same 100s wait is present for all KS mods when downloading RO so I assume it's not the SETI ckan being broken in some way.

**Comment by mdosogne** [comment]
Not sure if this is related or not, but I have been having trouble downloading recently. I've observed that if there are two downloads, CKAN will appear to hang (over 1min no progress, no significant network usage). On the other hand, if I select a single mod (with no dependencies or already-installed dependencies) then the download progresses quickly. Running on v1.6.6-0-g.

Command line:

$> mono ckan.exe install ContractConfigurator-UnmannedContracts
About to install...
 * ContractConfigurator-UnmannedContracts 0.2.3
 * SpacetuxSA 0.1.0
Continue? [Y/N] y
Downloading "https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3"
Downloading "https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0"

NOTE: One minute later with no bandwidth usage, I killed it.

$> mono ckan.exe install SpacetuxSA
About to install...
 * SpacetuxSA 0.1.0
Continue? [Y/N] y
Downloading "https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0"
Installing mod "SpacetuxSA 0.1.0"
Updating registry
Commiting filesystem changes
Rescanning GameData
Done!

NOTE: This took under 10 seconds.

$> mono ckan.exe install ContractConfigurator-UnmannedContracts
About to install...
 * ContractConfigurator-UnmannedContracts 0.2.3
Continue? [Y/N] y
Downloading "https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3"
Installing mod "ContractConfigurator-UnmannedContracts 0.2.3"
Updating registry
Commiting filesystem changes
Rescanning GameData
Done!

NOTE: This took under 10 seconds.

**Comment by Dazpoet** [comment]
@mdosogne would you mind attempting the same kind of install but do a `mono ckan.exe install --verbose <name of mod>` and show the log entries about downloading?

As is mentioned in the above discussion I've observed a 100s "lag" before downloads start so killing the process after a minute could "just" be that you're not waiting long enough for the fallback to kick in. If it only happens when downloading multiple mods that could be very helpful for us to know :)

**Comment by Saabstory88** [comment]
Running version v1.6.6-0-G-0000000 (beta) on Kubuntu

I have updated the certificate store. Looks like this may still be broken.

Follwing output from CKAN:

Downloading "https://kerbalstuff.com/mod/462/Advanced Jet Engine/download/2.0.3"
Downloading "https://kerbalstuff.com/mod/52/Ferram Aerospace Research/download/v0.14.6"
Downloading "https://kerbalstuff.com/mod/53/Kerbal Joint Reinforcement/download/v3.1.2"
Downloading "https://kerbalstuff.com/mod/11/Connected Living Space/download/1.1.2.0"
Downloading "https://kerbalstuff.com/mod/18/Hangar Extender/download/3.0"
Downloading "https://kerbalstuff.com/mod/71/RealChute Parachute Systems/download/1.3"
Downloading "https://kerbalstuff.com/mod/150/TextureReplacer/download/2.3.1"
Downloading "https://kerbalstuff.com/mod/344/TweakScale - Rescale Everything!/download/v1.52.1"

Oh no! Our download failed with a certificate error!

If you're on Linux, try running:
	mozroots --import --ask-remove
on the command-line to update your certificate store, and try again.

**Comment by Saabstory88** [comment]
Fixed the following from the forums. Might want to include this from the instrctions.
>@ghostnineone: I had the same problem you are describing. Installing the mentioned libcurl4-openssl-dev package via apt-get seems to have fixed it for me.

**Comment by Dazpoet** [comment]
Added to the basic troubleshooting guide in the wiki [here](https://github.com/KSP-CKAN/CKAN-support/wiki/Basic-troubleshooting#ckan-wont-start)

Will try to fit it under a better title in the next reformat of that page.

**Comment by mdosogne** [comment]
@Dazpoet 
*Summary:* installing each mod separately, from hitting enter on the command line to "Done!" took *8 seconds total* (including typing 'y' at the prompt twice). Installing the same two mods (one which depends no the other) takes several minutes (due to 100 second wait).

Note: I manually removed these mods from my cache before attempting each test. I've shortened the logs below (see [...]) to omit personal and reduce the spam a bit. I trust the rest will be useful.

```
$> mono ckan.exe install --verbose ContractConfigurator-UnmannedContracts. 
[...]
1355 [1] INFO CKAN.RelationshipResolver (null) - Resolving relationships for SpacetuxSA
About to install...
 * ContractConfigurator-UnmannedContracts 0.2.3
 * SpacetuxSA 0.1.0
Continue? [Y/N] y
Downloading "https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3"
Downloading "https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0"
3149 [7] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0: System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert (AlertLevel alertLevel, AlertDescription alertDesc) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (IAsyncResult result) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadFileCore (System.Uri address, System.String fileName, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.<DownloadFileAsync>m__1 (System.Object state) [0x00000] in <filename unknown>:0 
103024 [6] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3: System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadFileCore (System.Uri address, System.String fileName, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.<DownloadFileAsync>m__1 (System.Object state) [0x00000] in <filename unknown>:0 
103025 [6] INFO CKAN.NetAsyncDownloader (null) - All files finished downloading
103025 [6] INFO CKAN.NetAsyncDownloader (null) - Failed async download of https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3 attempting hacky fallback
103129 [6] INFO CKAN.Net (null) - Download failed, trying with curlsharp...
104237 [6] INFO CKAN.NetAsyncDownloader (null) - Failed async download of https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0 attempting hacky fallback
204247 [6] INFO CKAN.Net (null) - Download failed, trying with curlsharp...
Installing mod "ContractConfigurator-UnmannedContracts 0.2.3"204868 [1] INFO CKAN.ModuleInstaller (null) - Copying GameData/ContractPacks/spacetux/CHANGELOG
[...]
Installing mod "SpacetuxSA 0.1.0"204987 [1] INFO CKAN.ModuleInstaller (null) - Copying GameData/spacetux/
[...]
Updating registry
Commiting filesystem changes
Rescanning GameData205314 [1] INFO CKAN.Registry (null) - Not registering GameData/ModuleManager.2.5.10.dll, it belongs to ModuleManager
205316 [1] INFO CKAN.Registry (null) - Not registering GameData/ArcanumIndustries/Plugins/CostlyScience.dll, it belongs to FuelScience
[...]
Done!
```
Now, remove the mods, delete the cache and try again...
```
$> date; mono ckan.exe install --verbose SpacetuxSA; date; mono ckan.exe install --verbose ContractConfigurator-UnmannedContracts; date
Mon Mar 30 20:28:54 EDT 2015
141 [1] INFO CKAN.CmdLine.MainClass (null) - Verbose logging enabled
177 [1] INFO CKAN.KSP (null) - KSP found at ~/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program
179 [1] INFO CKAN.CmdLine.MainClass (null) - Using KSP install at ~/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program
895 [1] INFO CKAN.Registry (null) - Not registering GameData
[...]
About to install...
 * SpacetuxSA 0.1.0
Continue? [Y/N] y
Downloading "https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0"
2515 [6] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0: System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert (AlertLevel alertLevel, AlertDescription alertDesc) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (IAsyncResult result) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadFileCore (System.Uri address, System.String fileName, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.<DownloadFileAsync>m__1 (System.Object state) [0x00000] in <filename unknown>:0 
2516 [6] INFO CKAN.NetAsyncDownloader (null) - All files finished downloading
2516 [6] INFO CKAN.NetAsyncDownloader (null) - Failed async download of https://kerbalstuff.com/mod/656/Spacetux Shared Assets/download/0.1.0 attempting hacky fallback
2628 [6] INFO CKAN.Net (null) - Download failed, trying with curlsharp...
Installing mod "SpacetuxSA 0.1.0"3268 [1] INFO CKAN.ModuleInstaller (null) - Copying [...]

Updating registry
Commiting filesystem changes
Rescanning GameData3703 [1] INFO CKAN.Registry (null) - Not registering [...]
Done!
Mon Mar 30 20:28:58 EDT 2015
143 [1] INFO CKAN.CmdLine.MainClass [...]
1372 [1] INFO CKAN.RelationshipResolver (null) - Resolving relationships for ContractConfigurator-UnmannedContracts
1376 [1] INFO CKAN.RelationshipResolver (null) - Resolving relationships for ContractConfigurator-UnmannedContracts
About to install...
 * ContractConfigurator-UnmannedContracts 0.2.3
Continue? [Y/N] y
Downloading "https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3"
2267 [6] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3: System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.ProcessAlert (AlertLevel alertLevel, AlertDescription alertDesc) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslClientStream.EndNegotiateHandshake (IAsyncResult result) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadFileCore (System.Uri address, System.String fileName, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.<DownloadFileAsync>m__1 (System.Object state) [0x00000] in <filename unknown>:0 
2268 [6] INFO CKAN.NetAsyncDownloader (null) - All files finished downloading
2268 [6] INFO CKAN.NetAsyncDownloader (null) - Failed async download of https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3 attempting hacky fallback
2371 [6] INFO CKAN.Net (null) - Download failed, trying with curlsharp...
Installing mod "ContractConfigurator-UnmannedContracts 0.2.3"2873 [1] INFO CKAN.ModuleInstaller (null) - Copying [...]
Done!
Mon Mar 30 20:29:02 EDT 2015
```

**Comment by pjf** [comment]
> `103024 [6] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://kerbalstuff.com/mod/651/Contract Pack: Unmanned Contracts/download/0.2.3: System.Net.WebException: The request timed out`

Well, there's our problem. Whatever our NetAsyncDownloader is doing, it's failing quickly on the first download, and slowly (with a timeout) on the second.

Our ideal solution is to move everything over to curlsharp, since it's easy to use and seems to support all the encryption protocols reliably. There's an async mode that should be able to do everything we need.

A terrible hack would be to spot the first error that gets thrown, abort everything, and fall back to sequential curlsharp requests when that happens.

**Comment by darqen27** [comment]
Program still broken as far as I can see.. Have installed all dependencies and updated everything

1667 [1] ERROR CKAN.ModuleInstaller (null) - WebException while accessing https://api.github.com/repos/KSP-CKAN/CKAN/releases/latest: System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.ReadAll (System.Net.WebRequest request, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken) [0x00000] in <filename unknown>:0 
System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.ReadAll (System.Net.WebRequest request, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken) [0x00000] in <filename unknown>:0 
^C
darqen@MAINCENTER-LINUX:~/Desktop/KSP_linux$ kill mono
bash: kill: mono: arguments must be process or job IDs
darqen@MAINCENTER-LINUX:~/Desktop/KSP_linux$ kill list
bash: kill: list: arguments must be process or job IDs
darqen@MAINCENTER-LINUX:~/Desktop/KSP_linux$ kill -list
bash: kill: list: invalid signal specification
darqen@MAINCENTER-LINUX:~/Desktop/KSP_linux$ ./ckan.exe
1658 [1] ERROR CKAN.ModuleInstaller (null) - WebException while accessing https://api.github.com/repos/KSP-CKAN/CKAN/releases/latest: System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.ReadAll (System.Net.WebRequest request, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken) [0x00000] in <filename unknown>:0 
System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.RemoteValidation (Mono.Security.Protocol.Tls.ClientContext context, AlertDescription description) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()
  at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.ReadAll (System.Net.WebRequest request, System.Object userToken) [0x00000] in <filename unknown>:0 
  at System.Net.WebClient.DownloadDataCore (System.Uri address, System.Object userToken) [0x00000] in <filename unknown>:0

**Comment by Dazpoet** [comment]
This should now be resolved so I'll close this issue, great work everyone!
